# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/1440x1440/AttachedImage.qml) \
        $$quote($$BASEDIR/assets/1440x1440/ScreenContainer.qml) \
        $$quote($$BASEDIR/assets/720x1280/AttachedImage.qml) \
        $$quote($$BASEDIR/assets/720x1280/ScreenContainer.qml) \
        $$quote($$BASEDIR/assets/720x720/AttachedImage.qml) \
        $$quote($$BASEDIR/assets/720x720/ScreenContainer.qml) \
        $$quote($$BASEDIR/assets/768x1280/AttachedImage.qml) \
        $$quote($$BASEDIR/assets/768x1280/ScreenContainer.qml) \
        $$quote($$BASEDIR/assets/BrowserSheet.qml) \
        $$quote($$BASEDIR/assets/ConversationPage.qml) \
        $$quote($$BASEDIR/assets/DMAttachmentPage.qml) \
        $$quote($$BASEDIR/assets/DMConversationPage.qml) \
        $$quote($$BASEDIR/assets/DMInboxPage.qml) \
        $$quote($$BASEDIR/assets/DiscoverPage.qml) \
        $$quote($$BASEDIR/assets/ItemPage.qml) \
        $$quote($$BASEDIR/assets/ItemPage_scroll.qml) \
        $$quote($$BASEDIR/assets/ListPage.qml) \
        $$quote($$BASEDIR/assets/ListsPage.qml) \
        $$quote($$BASEDIR/assets/LoginSheet.qml) \
        $$quote($$BASEDIR/assets/NotificationsPage.qml) \
        $$quote($$BASEDIR/assets/ProfileMediaPage.qml) \
        $$quote($$BASEDIR/assets/Search.qml) \
        $$quote($$BASEDIR/assets/TopBlueBarText.qml) \
        $$quote($$BASEDIR/assets/TweetList.qml) \
        $$quote($$BASEDIR/assets/TweetSheet.qml) \
        $$quote($$BASEDIR/assets/UserProfile.qml) \
        $$quote($$BASEDIR/assets/UserProfile_androidlike.qml) \
        $$quote($$BASEDIR/assets/UserTweets.qml) \
        $$quote($$BASEDIR/assets/VideoPage.qml) \
        $$quote($$BASEDIR/assets/VisualStyle.bright/btn_compose_tweet.png) \
        $$quote($$BASEDIR/assets/VisualStyle.bright/btn_default_camera.png) \
        $$quote($$BASEDIR/assets/VisualStyle.bright/btn_default_gallery.png) \
        $$quote($$BASEDIR/assets/VisualStyle.bright/btn_emoji.png) \
        $$quote($$BASEDIR/assets/VisualStyle.bright/quoted_border.amd) \
        $$quote($$BASEDIR/assets/VisualStyle.bright/quoted_border.png) \
        $$quote($$BASEDIR/assets/VisualStyle.dark/btn_compose_tweet.png) \
        $$quote($$BASEDIR/assets/VisualStyle.dark/btn_default_camera.png) \
        $$quote($$BASEDIR/assets/VisualStyle.dark/btn_default_gallery.png) \
        $$quote($$BASEDIR/assets/VisualStyle.dark/btn_emoji.png) \
        $$quote($$BASEDIR/assets/VisualStyle.dark/quoted_border.amd) \
        $$quote($$BASEDIR/assets/VisualStyle.dark/quoted_border.png) \
        $$quote($$BASEDIR/assets/components/ArrowItemComponent.qml) \
        $$quote($$BASEDIR/assets/components/BigPic.qml) \
        $$quote($$BASEDIR/assets/components/DMCompose.qml) \
        $$quote($$BASEDIR/assets/components/DMConversationComponent.qml) \
        $$quote($$BASEDIR/assets/components/DMMessageComponent.qml) \
        $$quote($$BASEDIR/assets/components/DMPhotoCard.qml) \
        $$quote($$BASEDIR/assets/components/GifTweetComponent.qml) \
        $$quote($$BASEDIR/assets/components/GifTweetComponentMain.qml) \
        $$quote($$BASEDIR/assets/components/ImageTweetComponent.qml) \
        $$quote($$BASEDIR/assets/components/ImageTweetComponentMain.qml) \
        $$quote($$BASEDIR/assets/components/LoadingComponent.qml) \
        $$quote($$BASEDIR/assets/components/NotificationTweetComponent.qml) \
        $$quote($$BASEDIR/assets/components/ProfileHeaderBottom.qml) \
        $$quote($$BASEDIR/assets/components/ProfileHeaderTop.qml) \
        $$quote($$BASEDIR/assets/components/ProfilePic.qml) \
        $$quote($$BASEDIR/assets/components/ProfilePicMain.qml) \
        $$quote($$BASEDIR/assets/components/ProfilesList.qml) \
        $$quote($$BASEDIR/assets/components/QmlTimer.qml) \
        $$quote($$BASEDIR/assets/components/QuotedTweetComponent.qml) \
        $$quote($$BASEDIR/assets/components/RtContainer.qml) \
        $$quote($$BASEDIR/assets/components/TweetActionBar.qml) \
        $$quote($$BASEDIR/assets/components/TweetActionBarMain.qml) \
        $$quote($$BASEDIR/assets/components/TweetAuthorMain.qml) \
        $$quote($$BASEDIR/assets/components/TweetComponent.qml) \
        $$quote($$BASEDIR/assets/components/TweetComponentMain.qml) \
        $$quote($$BASEDIR/assets/components/TweetHeader.qml) \
        $$quote($$BASEDIR/assets/components/TweetItem.qml) \
        $$quote($$BASEDIR/assets/components/TweetTextHandler.qml) \
        $$quote($$BASEDIR/assets/components/VideoTweetComponent.qml) \
        $$quote($$BASEDIR/assets/components/VideoTweetComponentMain.qml) \
        $$quote($$BASEDIR/assets/components/Waiter.qml) \
        $$quote($$BASEDIR/assets/favorites.qml) \
        $$quote($$BASEDIR/assets/images/add_to_list_80x80.png) \
        $$quote($$BASEDIR/assets/images/bird_logo_white.png) \
        $$quote($$BASEDIR/assets/images/btn_default_photo_gallery.png) \
        $$quote($$BASEDIR/assets/images/btn_emoji_nature.png) \
        $$quote($$BASEDIR/assets/images/btn_emoji_objects.png) \
        $$quote($$BASEDIR/assets/images/btn_emoji_people.png) \
        $$quote($$BASEDIR/assets/images/btn_emoji_places.png) \
        $$quote($$BASEDIR/assets/images/btn_emoji_symbols.png) \
        $$quote($$BASEDIR/assets/images/btn_pressed_photo_gallery.png) \
        $$quote($$BASEDIR/assets/images/bubble_arrow_blue.png) \
        $$quote($$BASEDIR/assets/images/bubble_arrow_gray.png) \
        $$quote($$BASEDIR/assets/images/card_null.png) \
        $$quote($$BASEDIR/assets/images/chat_bubble_blue.amd) \
        $$quote($$BASEDIR/assets/images/chat_bubble_blue.png) \
        $$quote($$BASEDIR/assets/images/chat_bubble_gray.amd) \
        $$quote($$BASEDIR/assets/images/chat_bubble_gray.png) \
        $$quote($$BASEDIR/assets/images/delete_80x80.png) \
        $$quote($$BASEDIR/assets/images/emoji_nature.xml) \
        $$quote($$BASEDIR/assets/images/emoji_objects.xml) \
        $$quote($$BASEDIR/assets/images/emoji_people.xml) \
        $$quote($$BASEDIR/assets/images/emoji_places.xml) \
        $$quote($$BASEDIR/assets/images/emoji_symbols.xml) \
        $$quote($$BASEDIR/assets/images/heart.png) \
        $$quote($$BASEDIR/assets/images/heart_grey.png) \
        $$quote($$BASEDIR/assets/images/heart_red.png) \
        $$quote($$BASEDIR/assets/images/home_80x80.png) \
        $$quote($$BASEDIR/assets/images/ic_open.png) \
        $$quote($$BASEDIR/assets/images/ic_resume.png) \
        $$quote($$BASEDIR/assets/images/ic_save.png) \
        $$quote($$BASEDIR/assets/images/icn_compose_focused_100x100.png) \
        $$quote($$BASEDIR/assets/images/icn_compose_white_100x100.png) \
        $$quote($$BASEDIR/assets/images/icn_search_focused_100x100.png) \
        $$quote($$BASEDIR/assets/images/icn_search_white_100x100.png) \
        $$quote($$BASEDIR/assets/images/image_mask.amd) \
        $$quote($$BASEDIR/assets/images/image_mask.png) \
        $$quote($$BASEDIR/assets/images/image_mask_dark.amd) \
        $$quote($$BASEDIR/assets/images/image_mask_dark.png) \
        $$quote($$BASEDIR/assets/images/logo.png) \
        $$quote($$BASEDIR/assets/images/logout.png) \
        $$quote($$BASEDIR/assets/images/me_80x80.png) \
        $$quote($$BASEDIR/assets/images/messages_80x80.png) \
        $$quote($$BASEDIR/assets/images/new_msg.png) \
        $$quote($$BASEDIR/assets/images/notifications_80x80.png) \
        $$quote($$BASEDIR/assets/images/notifications_active_80x80.png) \
        $$quote($$BASEDIR/assets/images/play-50x50.png) \
        $$quote($$BASEDIR/assets/images/play.png) \
        $$quote($$BASEDIR/assets/images/profile/avatar_border.amd) \
        $$quote($$BASEDIR/assets/images/profile/avatar_border.png) \
        $$quote($$BASEDIR/assets/images/profile/dark_background.png) \
        $$quote($$BASEDIR/assets/images/profile/follow.png) \
        $$quote($$BASEDIR/assets/images/profile/icn_lock_sm.png) \
        $$quote($$BASEDIR/assets/images/profile/list_item_chevron.png) \
        $$quote($$BASEDIR/assets/images/profile/profile_pic_gradient.png) \
        $$quote($$BASEDIR/assets/images/profile/profile_position-gray.png) \
        $$quote($$BASEDIR/assets/images/profile/profile_position-white.png) \
        $$quote($$BASEDIR/assets/images/profile/profile_position.png) \
        $$quote($$BASEDIR/assets/images/profile/tweet_tile_bkg-pressed.png) \
        $$quote($$BASEDIR/assets/images/profile/tweet_tile_bkg.png) \
        $$quote($$BASEDIR/assets/images/profile/tweet_tile_bkg_invers.png) \
        $$quote($$BASEDIR/assets/images/profile/unfollow.png) \
        $$quote($$BASEDIR/assets/images/profile/verified_profile.png) \
        $$quote($$BASEDIR/assets/images/reply_hvr_80x80.png) \
        $$quote($$BASEDIR/assets/images/reply_on_hvr_80x80.png) \
        $$quote($$BASEDIR/assets/images/retweet_80x80.png) \
        $$quote($$BASEDIR/assets/images/retweet_green.png) \
        $$quote($$BASEDIR/assets/images/retweet_grey.png) \
        $$quote($$BASEDIR/assets/images/retweet_on_80x80.png) \
        $$quote($$BASEDIR/assets/images/rounded9slice.amd) \
        $$quote($$BASEDIR/assets/images/rounded9slice.png) \
        $$quote($$BASEDIR/assets/images/search_cancel.png) \
        $$quote($$BASEDIR/assets/images/share_tweet.png) \
        $$quote($$BASEDIR/assets/images/share_tweet_hvr.png) \
        $$quote($$BASEDIR/assets/images/twitterheart.png) \
        $$quote($$BASEDIR/assets/main.qml) \
        $$quote($$BASEDIR/assets/tl.qml) \
        $$quote($$BASEDIR/assets/user.qml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/Conversation.cpp) \
        $$quote($$BASEDIR/src/ConversationApi.cpp) \
        $$quote($$BASEDIR/src/DMApi.cpp) \
        $$quote($$BASEDIR/src/DiscoverApi.cpp) \
        $$quote($$BASEDIR/src/ListApi.cpp) \
        $$quote($$BASEDIR/src/NotificationsApi.cpp) \
        $$quote($$BASEDIR/src/ProfileApi.cpp) \
        $$quote($$BASEDIR/src/QJson4/QJsonArray.cpp) \
        $$quote($$BASEDIR/src/QJson4/QJsonDocument.cpp) \
        $$quote($$BASEDIR/src/QJson4/QJsonObject.cpp) \
        $$quote($$BASEDIR/src/QJson4/QJsonParseError.cpp) \
        $$quote($$BASEDIR/src/QJson4/QJsonParser.cpp) \
        $$quote($$BASEDIR/src/QJson4/QJsonValue.cpp) \
        $$quote($$BASEDIR/src/QJson4/QJsonValueRef.cpp) \
        $$quote($$BASEDIR/src/QtCurl/CurlEasy.cpp) \
        $$quote($$BASEDIR/src/QtCurl/CurlMulti.cpp) \
        $$quote($$BASEDIR/src/RetweetDialog.cpp) \
        $$quote($$BASEDIR/src/SearchApi.cpp) \
        $$quote($$BASEDIR/src/TimelineBase.cpp) \
        $$quote($$BASEDIR/src/TweetApi.cpp) \
        $$quote($$BASEDIR/src/TwitterApiBase.cpp) \
        $$quote($$BASEDIR/src/WebImageView/AuthorizedWebImageView.cpp) \
        $$quote($$BASEDIR/src/WebImageView/WebImageView.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp) \
        $$quote($$BASEDIR/src/o2/o0baseauth.cpp) \
        $$quote($$BASEDIR/src/o2/o0settingsstore.cpp) \
        $$quote($$BASEDIR/src/o2/o1.cpp) \
        $$quote($$BASEDIR/src/o2/o1requestor.cpp) \
        $$quote($$BASEDIR/src/o2/o1timedreply.cpp) \
        $$quote($$BASEDIR/src/o2/o2.cpp) \
        $$quote($$BASEDIR/src/o2/o2gft.cpp) \
        $$quote($$BASEDIR/src/o2/o2reply.cpp) \
        $$quote($$BASEDIR/src/o2/o2replyserver.cpp) \
        $$quote($$BASEDIR/src/o2/o2requestor.cpp) \
        $$quote($$BASEDIR/src/o2/o2simplecrypt.cpp) \
        $$quote($$BASEDIR/src/o2/oxtwitter.cpp) \
        $$quote($$BASEDIR/src/twitterapi.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/Conversation.hpp) \
        $$quote($$BASEDIR/src/ConversationApi.hpp) \
        $$quote($$BASEDIR/src/DMApi.hpp) \
        $$quote($$BASEDIR/src/DiscoverApi.hpp) \
        $$quote($$BASEDIR/src/ListApi.hpp) \
        $$quote($$BASEDIR/src/NotificationsApi.hpp) \
        $$quote($$BASEDIR/src/ProfileApi.hpp) \
        $$quote($$BASEDIR/src/QJson4/QJsonArray.h) \
        $$quote($$BASEDIR/src/QJson4/QJsonDocument.h) \
        $$quote($$BASEDIR/src/QJson4/QJsonObject.h) \
        $$quote($$BASEDIR/src/QJson4/QJsonParseError.h) \
        $$quote($$BASEDIR/src/QJson4/QJsonParser.h) \
        $$quote($$BASEDIR/src/QJson4/QJsonRoot.h) \
        $$quote($$BASEDIR/src/QJson4/QJsonValue.h) \
        $$quote($$BASEDIR/src/QJson4/QJsonValueRef.h) \
        $$quote($$BASEDIR/src/QtCurl/CurlEasy.h) \
        $$quote($$BASEDIR/src/QtCurl/CurlMulti.h) \
        $$quote($$BASEDIR/src/RetweetDialog.hpp) \
        $$quote($$BASEDIR/src/SearchApi.hpp) \
        $$quote($$BASEDIR/src/TimelineBase.hpp) \
        $$quote($$BASEDIR/src/TweetApi.hpp) \
        $$quote($$BASEDIR/src/TwitterApiBase.hpp) \
        $$quote($$BASEDIR/src/WebImageView/AuthorizedWebImageView.hpp) \
        $$quote($$BASEDIR/src/WebImageView/WebImageView.h) \
        $$quote($$BASEDIR/src/applicationui.hpp) \
        $$quote($$BASEDIR/src/legacysecret.h) \
        $$quote($$BASEDIR/src/o2/o0abstractstore.h) \
        $$quote($$BASEDIR/src/o2/o0baseauth.h) \
        $$quote($$BASEDIR/src/o2/o0export.h) \
        $$quote($$BASEDIR/src/o2/o0globals.h) \
        $$quote($$BASEDIR/src/o2/o0requestparameter.h) \
        $$quote($$BASEDIR/src/o2/o0settingsstore.h) \
        $$quote($$BASEDIR/src/o2/o0simplecrypt.h) \
        $$quote($$BASEDIR/src/o2/o1.h) \
        $$quote($$BASEDIR/src/o2/o1freshbooks.h) \
        $$quote($$BASEDIR/src/o2/o1requestor.h) \
        $$quote($$BASEDIR/src/o2/o1timedreply.h) \
        $$quote($$BASEDIR/src/o2/o1twitter.h) \
        $$quote($$BASEDIR/src/o2/o2.h) \
        $$quote($$BASEDIR/src/o2/o2gft.h) \
        $$quote($$BASEDIR/src/o2/o2reply.h) \
        $$quote($$BASEDIR/src/o2/o2replyserver.h) \
        $$quote($$BASEDIR/src/o2/o2requestor.h) \
        $$quote($$BASEDIR/src/o2/oxtwitter.h) \
        $$quote($$BASEDIR/src/secret.h) \
        $$quote($$BASEDIR/src/twitterapi.hpp)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/QJson4/*.c) \
        $$quote($$BASEDIR/../src/QJson4/*.c++) \
        $$quote($$BASEDIR/../src/QJson4/*.cc) \
        $$quote($$BASEDIR/../src/QJson4/*.cpp) \
        $$quote($$BASEDIR/../src/QJson4/*.cxx) \
        $$quote($$BASEDIR/../src/QtCurl/*.c) \
        $$quote($$BASEDIR/../src/QtCurl/*.c++) \
        $$quote($$BASEDIR/../src/QtCurl/*.cc) \
        $$quote($$BASEDIR/../src/QtCurl/*.cpp) \
        $$quote($$BASEDIR/../src/QtCurl/*.cxx) \
        $$quote($$BASEDIR/../src/WebImageView/*.c) \
        $$quote($$BASEDIR/../src/WebImageView/*.c++) \
        $$quote($$BASEDIR/../src/WebImageView/*.cc) \
        $$quote($$BASEDIR/../src/WebImageView/*.cpp) \
        $$quote($$BASEDIR/../src/WebImageView/*.cxx) \
        $$quote($$BASEDIR/../src/o2/*.c) \
        $$quote($$BASEDIR/../src/o2/*.c++) \
        $$quote($$BASEDIR/../src/o2/*.cc) \
        $$quote($$BASEDIR/../src/o2/*.cpp) \
        $$quote($$BASEDIR/../src/o2/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/1440x1440/*.qml) \
        $$quote($$BASEDIR/../assets/1440x1440/*.js) \
        $$quote($$BASEDIR/../assets/1440x1440/*.qs) \
        $$quote($$BASEDIR/../assets/720x1280/*.qml) \
        $$quote($$BASEDIR/../assets/720x1280/*.js) \
        $$quote($$BASEDIR/../assets/720x1280/*.qs) \
        $$quote($$BASEDIR/../assets/720x720/*.qml) \
        $$quote($$BASEDIR/../assets/720x720/*.js) \
        $$quote($$BASEDIR/../assets/720x720/*.qs) \
        $$quote($$BASEDIR/../assets/768x1280/*.qml) \
        $$quote($$BASEDIR/../assets/768x1280/*.js) \
        $$quote($$BASEDIR/../assets/768x1280/*.qs) \
        $$quote($$BASEDIR/../assets/VisualStyle.bright/*.qml) \
        $$quote($$BASEDIR/../assets/VisualStyle.bright/*.js) \
        $$quote($$BASEDIR/../assets/VisualStyle.bright/*.qs) \
        $$quote($$BASEDIR/../assets/VisualStyle.dark/*.qml) \
        $$quote($$BASEDIR/../assets/VisualStyle.dark/*.js) \
        $$quote($$BASEDIR/../assets/VisualStyle.dark/*.qs) \
        $$quote($$BASEDIR/../assets/components/*.qml) \
        $$quote($$BASEDIR/../assets/components/*.js) \
        $$quote($$BASEDIR/../assets/components/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs) \
        $$quote($$BASEDIR/../assets/images/profile/*.qml) \
        $$quote($$BASEDIR/../assets/images/profile/*.js) \
        $$quote($$BASEDIR/../assets/images/profile/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
